# Generated by Django 4.2.24 on 2025-10-06 23:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Entrada')),
                ('nome', models.CharField(default='(Nome não fornecido)', max_length=200, verbose_name='Nome')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Série')),
                ('preco_aproximado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Aproximado')),
                ('situacao', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('descartado', 'Descartado')], default='disponivel', max_length=20, verbose_name='Situação')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('motivo_saida', models.TextField(blank=True, null=True, verbose_name='Motivo de Saída')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('codigo_patrimonio', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Código de Patrimônio')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='equipamentos_fotos/', verbose_name='Foto do Equipamento')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.categoria', verbose_name='Categoria')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.departamento', verbose_name='Departamento')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.localizacao', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'permissions': [('can_export_csv', 'Pode exportar relatórios CSV de equipamentos')],
            },
        ),
    ]
