# Generated by Django 4.2.24 on 2025-10-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'permissions': [('can_export_csv', 'Pode exportar relatórios CSV de equipamentos'), ('can_print_label', 'Pode imprimir etiquetas de equipamentos')], 'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
    ]
