# Generated by Django 4.2.24 on 2026-06-16 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_equipamento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='core.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='core.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='localizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='core.localizacao', verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='motivo_saida',
            field=models.TextField(blank=True, default='', verbose_name='Motivo de Saída'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
