# Generated by Django 4.2.24 on 2026-06-22 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historicoequipamento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='vida_util_anos',
            field=models.PositiveIntegerField(default=5, help_text='Para cálculo de depreciação.', verbose_name='Vida Útil (Anos)'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_entrada',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='situacao',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('descartado', 'Descartado')], db_index=True, default='disponivel', max_length=20, verbose_name='Situação'),
        ),
    ]
